package com.smartjobtracker.model;
import jakarta.persistence.*; import java.time.OffsetDateTime;
@Entity @Table(name="gmail_connections", uniqueConstraints=@UniqueConstraint(columnNames="user_id"))
public class GmailConnection {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @Column(name="user_id",nullable=false) private Long userId;
 @Column(name="google_email") private String googleEmail; @Column(name="encrypted_refresh_token",columnDefinition="text") private String encryptedRefreshToken;
 @Column(name="encrypted_access_token",columnDefinition="text") private String encryptedAccessToken; @Column(name="access_token_expires_at") private OffsetDateTime accessTokenExpiresAt;
 @Column(nullable=false) private String status; @Column(name="oauth_state") private String oauthState; @Column(name="state_expires_at") private OffsetDateTime stateExpiresAt;
 @Column(name="last_history_id") private String lastHistoryId; @Column(name="connected_at") private OffsetDateTime connectedAt; @Column(name="updated_at",nullable=false) private OffsetDateTime updatedAt=OffsetDateTime.now();
 public Long getId(){return id;} public void setId(Long v){id=v;} public Long getUserId(){return userId;} public void setUserId(Long v){userId=v;} public String getGoogleEmail(){return googleEmail;} public void setGoogleEmail(String v){googleEmail=v;} public String getEncryptedRefreshToken(){return encryptedRefreshToken;} public void setEncryptedRefreshToken(String v){encryptedRefreshToken=v;} public String getEncryptedAccessToken(){return encryptedAccessToken;} public void setEncryptedAccessToken(String v){encryptedAccessToken=v;} public OffsetDateTime getAccessTokenExpiresAt(){return accessTokenExpiresAt;} public void setAccessTokenExpiresAt(OffsetDateTime v){accessTokenExpiresAt=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public String getOauthState(){return oauthState;} public void setOauthState(String v){oauthState=v;} public OffsetDateTime getStateExpiresAt(){return stateExpiresAt;} public void setStateExpiresAt(OffsetDateTime v){stateExpiresAt=v;} public String getLastHistoryId(){return lastHistoryId;} public void setLastHistoryId(String v){lastHistoryId=v;} public OffsetDateTime getConnectedAt(){return connectedAt;} public void setConnectedAt(OffsetDateTime v){connectedAt=v;} public OffsetDateTime getUpdatedAt(){return updatedAt;} public void setUpdatedAt(OffsetDateTime v){updatedAt=v;}
}