import React, { useEffect, useState } from 'react'
import { Check, ClipboardCheck, FileText, X } from 'lucide-react'
import api from '../api/axios'
import Layout from '../components/Layout'
import { getApplicationProfile, saveApplicationProfile, prepareApplication, decideApplicationSuggestion } from '../api/applicationPreparation'

const fieldTypes = ['NAME', 'EMAIL', 'PHONE', 'EDUCATION', 'EXPERIENCE', 'SKILLS', 'GITHUB', 'LINKEDIN', 'PORTFOLIO', 'RESUME']
const emptyProfile = { fullName: '', email: '', phone: '', education: '', experience: '', skills: '', githubUrl: '', linkedinUrl: '', portfolioUrl: '', resumeId: null }

export default function ApplicationPreparation() {
  const [resumes, setResumes] = useState([]); const [profile, setProfile] = useState(emptyProfile); const [resumeId, setResumeId] = useState(''); const [jobDescription, setJobDescription] = useState(''); const [fields, setFields] = useState([{ externalField: 'name', fieldType: 'NAME' }, { externalField: 'email', fieldType: 'EMAIL' }, { externalField: 'resume', fieldType: 'RESUME' }]); const [preparation, setPreparation] = useState(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('')
  useEffect(() => { load() }, [])
  async function load() { try { const [resumeResult, profileResult] = await Promise.all([api.get('/resume/me'), getApplicationProfile()]); setResumes(resumeResult.data); if (resumeResult.data[0]) setResumeId(resumeResult.data[0].id); if (profileResult.status !== 204) setProfile(profileResult.data) } catch (e) { console.error(e) } }
  async function saveProfile() { try { await saveApplicationProfile({ ...profile, resumeId: resumeId ? Number(resumeId) : null }); setNotice('Application profile saved.'); } catch (e) { setError('Could not save your profile.') } }
  async function prepare(e) { e.preventDefault(); setError(''); setNotice(''); if (!resumeId || !jobDescription.trim()) { setError('Select a resume and paste a job description.'); return } try { setBusy(true); setPreparation((await prepareApplication({ resumeId: Number(resumeId), jobDescription, mappings: fields.filter(item => item.externalField.trim()) })).data) } catch (e) { setError('Could not prepare the application.'); console.error(e) } finally { setBusy(false) } }
  async function decide(id, decision) { try { const updated = (await decideApplicationSuggestion(id, decision)).data; setPreparation({ ...preparation, suggestions: preparation.suggestions.map(item => item.id === id ? updated : item) }) } catch (e) { console.error(e) } }
  function addField() { setFields([...fields, { externalField: '', fieldType: 'NAME' }]) }
  return <Layout title="Application preparation" subtitle="Review grounded answers before you apply">
    <div className="grid lg:grid-cols-3 gap-6">
      <section className="bg-surface border border-line rounded-xl2 shadow-card p-5 h-fit space-y-5">
        <div><h2 className="font-display text-[15px] text-ink mb-3">Application profile</h2><p className="text-xs text-muted mb-3">Only facts you provide or that are extracted from your profile can become answers.</p><div className="space-y-2">{[['fullName','Name'],['email','Email'],['phone','Phone'],['githubUrl','GitHub'],['linkedinUrl','LinkedIn'],['portfolioUrl','Portfolio']].map(([key,label]) => <input key={key} className="w-full px-3 py-2 rounded-lg border border-line bg-paper text-sm" placeholder={label} value={profile[key] || ''} onChange={(e) => setProfile({ ...profile, [key]: e.target.value })} />)}<textarea rows={2} className="w-full px-3 py-2 rounded-lg border border-line bg-paper text-sm resize-none" placeholder="Education" value={profile.education || ''} onChange={(e) => setProfile({ ...profile, education: e.target.value })} /><textarea rows={2} className="w-full px-3 py-2 rounded-lg border border-line bg-paper text-sm resize-none" placeholder="Experience" value={profile.experience || ''} onChange={(e) => setProfile({ ...profile, experience: e.target.value })} /><textarea rows={2} className="w-full px-3 py-2 rounded-lg border border-line bg-paper text-sm resize-none" placeholder="Skills" value={profile.skills || ''} onChange={(e) => setProfile({ ...profile, skills: e.target.value })} /></div><button onClick={saveProfile} className="mt-3 px-3 py-2 rounded-lg border border-line text-sm font-medium text-ink">Save profile</button></div>
        <form onSubmit={prepare}><h2 className="font-display text-[15px] text-ink mb-3">Target form</h2><select required className="w-full mb-2 px-3 py-2 rounded-lg border border-line bg-paper text-sm" value={resumeId} onChange={(e) => setResumeId(e.target.value)}><option value="">Original resume</option>{resumes.map((resume) => <option key={resume.id} value={resume.id}>{resume.fileName}</option>)}</select><textarea required rows={7} className="w-full px-3 py-2 rounded-lg border border-line bg-paper text-sm resize-none" placeholder="Paste job description" value={jobDescription} onChange={(e) => setJobDescription(e.target.value)} /><h3 className="text-xs font-medium text-muted mt-3 mb-2">Form field mapping</h3>{fields.map((field, index) => <div key={index} className="flex gap-2 mb-2"><input required className="min-w-0 flex-1 px-2 py-2 rounded-lg border border-line bg-paper text-xs" placeholder="External field label" value={field.externalField} onChange={(e) => setFields(fields.map((item, i) => i === index ? { ...item, externalField: e.target.value } : item))} /><select className="w-28 px-1 py-2 rounded-lg border border-line bg-paper text-xs" value={field.fieldType} onChange={(e) => setFields(fields.map((item, i) => i === index ? { ...item, fieldType: e.target.value } : item))}>{fieldTypes.map((type) => <option key={type}>{type}</option>)}</select></div>)}<button type="button" onClick={addField} className="text-xs text-ink underline">Add field mapping</button>{error && <p className="text-sm text-status-rejected mt-3">{error}</p>}<button disabled={busy} className="w-full mt-3 inline-flex items-center justify-center gap-1.5 bg-ink text-white text-sm font-medium px-4 py-2.5 rounded-lg disabled:opacity-50"><ClipboardCheck size={15} />{busy ? 'Preparing...' : 'Prepare for review'}</button></form>
      </section>
      <section className="lg:col-span-2 space-y-4">{notice && <p className="text-sm text-status-offer">{notice}</p>}{!preparation ? <div className="bg-surface border border-dashed border-line rounded-xl2 p-10 text-center text-sm text-muted">Mapped answers and grounded suggestions will appear here. Nothing will be submitted automatically.</div> : <><div className="bg-surface border border-line rounded-xl2 p-5"><h2 className="font-display text-[15px] text-ink mb-2">Review answers</h2><p className="text-xs text-muted">Every answer includes its source evidence. CAPTCHA, authentication, and submission stay with you.</p></div>{preparation.suggestions.map((item) => <article key={item.id} className="bg-surface border border-line rounded-xl2 shadow-card p-5"><div className="flex justify-between gap-3 mb-2"><span className="text-xs font-medium text-muted">{item.externalField} · {item.fieldType}</span><span className="text-xs text-muted">{item.decision}</span></div><div className="grid md:grid-cols-2 gap-3"><div className="border border-line rounded-lg p-3"><div className="text-xs text-muted mb-1">Suggested answer</div><p className="text-sm text-ink whitespace-pre-wrap">{item.suggestedValue}</p></div><div className="border border-status-offer/30 bg-status-offerSoft/30 rounded-lg p-3"><div className="text-xs text-muted mb-1">Source evidence</div><p className="text-sm text-ink whitespace-pre-wrap">{item.sourceEvidence}</p></div></div><p className="text-xs text-muted mt-3">{item.rationale}</p><div className="flex gap-2 mt-3"><button onClick={() => decide(item.id, 'ACCEPTED')} className="inline-flex items-center gap-1 px-3 py-2 rounded-lg bg-status-offerSoft text-status-offer text-xs font-medium"><Check size={14} />Accept</button><button onClick={() => decide(item.id, 'REJECTED')} className="inline-flex items-center gap-1 px-3 py-2 rounded-lg bg-status-rejectedSoft text-status-rejected text-xs font-medium"><X size={14} />Reject</button></div></article>)}</>}{preparation && preparation.suggestions.length === 0 && <div className="bg-surface border border-line rounded-xl2 p-5 text-sm text-muted">No verified answer is available for these mapped fields. Nothing was invented.</div>}<div className="bg-surface border border-line rounded-xl2 p-5 flex items-start gap-2"><FileText size={16} className="text-muted mt-0.5" /><p className="text-xs text-muted">This is a preparation and review workspace only. There is no automatic browser submission.</p></div></section>
    </div>
  </Layout>
}